package View;
import Model.ModelUsuario;
import Estrutura.PessoaComparatorPorNome;
import Estrutura.UsuarioComparatorPorInstituicao;
import java.util.Collections;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author dklug
 */
public class ViewManutencaoUsuario extends javax.swing.JFrame {
    
    private View view;
    String modo;

    /**
     * Creates new form ViewUsuario
     */
 ViewManutencaoUsuario(View view) {
        this.view = view;
        initComponents();
        LoadTable();
    }

    private void LoadTable() {
        DefaultTableModel modelo = new DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Nome", "Instituição"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        };
        for (int i = 0; i < this.view.getUsuarios().size(); i++) {
            Object linha[] = new Object[] { this.view.getUsuarios().get(i).getCodigo(),
                                                            this.view.getUsuarios().get(i).getNome(),
                                                            this.view.getUsuarios().get(i).getInstituicao()};
            modelo.addRow(linha);
        }
        tbUsuario.setModel(modelo);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbUsuario = new javax.swing.JTable();
        btAdicionar = new javax.swing.JButton();
        btEditar = new javax.swing.JButton();
        btExcluir = new javax.swing.JButton();
        lbNome = new javax.swing.JLabel();
        lbInstituicao = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tfNome = new javax.swing.JTextPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        tfInstituicao = new javax.swing.JTextPane();
        btSalvar = new javax.swing.JButton();
        btCancelar = new javax.swing.JButton();
        btOrdCod = new javax.swing.JButton();
        btOrdNome = new javax.swing.JButton();
        btOrdInst = new javax.swing.JButton();
        lbOrdem = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tbUsuario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Nome", "Instituição"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbUsuario.setColumnSelectionAllowed(false);
        tbUsuario.getTableHeader().setReorderingAllowed(false);
        tbUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbUsuarioMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbUsuario);
        if (tbUsuario.getColumnModel().getColumnCount() > 0) {
            tbUsuario.getColumnModel().getColumn(0).setResizable(false);
        }

        btAdicionar.setText("Adicionar");
        btAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAdicionarActionPerformed(evt);
            }
        });

        btEditar.setText("Editar");
        btEditar.setEnabled(false);
        btEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEditarActionPerformed(evt);
            }
        });

        btExcluir.setText("Excluir");
        btExcluir.setEnabled(false);
        btExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExcluirActionPerformed(evt);
            }
        });

        lbNome.setText("Nome:");

        lbInstituicao.setText("Instituição:");

        tfNome.setEnabled(false);
        jScrollPane2.setViewportView(tfNome);

        tfInstituicao.setEnabled(false);
        jScrollPane3.setViewportView(tfInstituicao);

        btSalvar.setText("Salvar");
        btSalvar.setEnabled(false);
        btSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalvarActionPerformed(evt);
            }
        });

        btCancelar.setText("Cancelar");
        btCancelar.setToolTipText("");
        btCancelar.setEnabled(false);
        btCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelarActionPerformed(evt);
            }
        });

        btOrdCod.setText("Código");
        btOrdCod.setPreferredSize(new java.awt.Dimension(155, 26));
        btOrdCod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btOrdCodActionPerformed(evt);
            }
        });

        btOrdNome.setText("Nome");
        btOrdNome.setPreferredSize(new java.awt.Dimension(155, 26));
        btOrdNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btOrdNomeActionPerformed(evt);
            }
        });

        btOrdInst.setText("Instituição");
        btOrdInst.setPreferredSize(new java.awt.Dimension(155, 26));
        btOrdInst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btOrdInstActionPerformed(evt);
            }
        });

        lbOrdem.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbOrdem.setText("Ordenar por:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbOrdem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btAdicionar, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(67, 67, 67)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(btSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(lbInstituicao)
                                            .addComponent(lbNome))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btOrdCod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btOrdNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btOrdInst, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(lbOrdem)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btOrdCod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btOrdNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btOrdInst, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btAdicionar)
                    .addComponent(btEditar)
                    .addComponent(btExcluir))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbNome))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbInstituicao)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btSalvar)
                    .addComponent(btCancelar))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btOrdInstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btOrdInstActionPerformed
        Collections.sort(view.getUsuarios(), new UsuarioComparatorPorInstituicao());
        LoadTable();
    }//GEN-LAST:event_btOrdInstActionPerformed

    private void btOrdNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btOrdNomeActionPerformed
        Collections.sort(view.getUsuarios(), new PessoaComparatorPorNome());
        LoadTable();
    }//GEN-LAST:event_btOrdNomeActionPerformed

    private void btOrdCodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btOrdCodActionPerformed
        Collections.sort(view.getUsuarios());
        LoadTable();
    }//GEN-LAST:event_btOrdCodActionPerformed

    private void btCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelarActionPerformed
        modo = "Visualizar";
        manipularInterface();
    }//GEN-LAST:event_btCancelarActionPerformed

    private void btSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalvarActionPerformed
        if (modo.equals("Novo")) {
            ModelUsuario usuario = new ModelUsuario(tfNome.getText(), tfInstituicao.getText());
            this.view.salvarUsuario(usuario);
        } else if (modo.equals("Editar")) {
            int index = tbUsuario.getSelectedRow();
            ModelUsuario usuario = new ModelUsuario(this.view.getUsuarios().get(index).getCodigo(),tfNome.getText(), tfInstituicao.getText());
            this.view.editarUsuario(usuario);
        }

        modo = "Visualizar";
        manipularInterface();
        LoadTable();
    }//GEN-LAST:event_btSalvarActionPerformed

    private void btExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExcluirActionPerformed

        int index = tbUsuario.getSelectedRow();
        if (index >= 0 && index < this.view.getUsuarios().size()) {
            int confirmacao = JOptionPane.YES_NO_OPTION;
            int excluir = JOptionPane.showConfirmDialog (null, "Deseja excluir esse usuário?","Warning",confirmacao);
            if(excluir == JOptionPane.YES_OPTION) {
                this.view.excluirUsuario(this.view.getUsuarios().get(index).getCodigo());
            }
        }
        LoadTable();
        modo = "Visualizar";
        manipularInterface();
    }//GEN-LAST:event_btExcluirActionPerformed

    private void btEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEditarActionPerformed
        modo = "Editar";
        manipularInterface();
    }//GEN-LAST:event_btEditarActionPerformed

    private void btAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAdicionarActionPerformed
        modo = "Novo";
        manipularInterface();
    }//GEN-LAST:event_btAdicionarActionPerformed

    private void tbUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbUsuarioMouseClicked
        int index = tbUsuario.getSelectedRow();
        if (index >= 0 && index < this.view.getUsuarios().size()) {
            modo = "Selecionar";
            manipularInterface();
            tfNome.setText(this.view.getUsuarios().get(index).getNome());
            tfInstituicao.setText(this.view.getUsuarios().get(index).getInstituicao());
        }
    }//GEN-LAST:event_tbUsuarioMouseClicked

    private void manipularInterface () {
        switch (modo) {
            case "Visualizar":
                btAdicionar.setEnabled(true);
                btEditar.setEnabled(false);
                btExcluir.setEnabled(false);
                btSalvar.setEnabled(false);
                btCancelar.setEnabled(false);
                tfNome.setEnabled(false);
                tfInstituicao.setEnabled(false);
                tfNome.setText("");
                tfInstituicao.setText("");
                tbUsuario.clearSelection();
                break;
                
            case "Selecionar":
                btAdicionar.setEnabled(true);
                btEditar.setEnabled(true);
                btExcluir.setEnabled(true);
                btSalvar.setEnabled(false);
                btCancelar.setEnabled(false);
                tfNome.setEnabled(false);
                tfInstituicao.setEnabled(false);
                break;
            
            case "Novo":
                btAdicionar.setEnabled(false);
                btEditar.setEnabled(false);
                btExcluir.setEnabled(false);
                btSalvar.setEnabled(true);
                btCancelar.setEnabled(true);
                tfNome.setEnabled(true);
                tfInstituicao.setEnabled(true);
                tfNome.setText("");
                tfInstituicao.setText("");
                tbUsuario.clearSelection();
                break;
            
            case "Editar":
                btAdicionar.setEnabled(false);
                btEditar.setEnabled(false);
                btExcluir.setEnabled(false);
                btSalvar.setEnabled(true);
                btCancelar.setEnabled(true);
                tfNome.setEnabled(true);
                tfInstituicao.setEnabled(true);
                break;
                
            default: System.out.println("Modo inválido");
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAdicionar;
    private javax.swing.JButton btCancelar;
    private javax.swing.JButton btEditar;
    private javax.swing.JButton btExcluir;
    private javax.swing.JButton btOrdCod;
    private javax.swing.JButton btOrdInst;
    private javax.swing.JButton btOrdNome;
    private javax.swing.JButton btSalvar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lbInstituicao;
    private javax.swing.JLabel lbNome;
    private javax.swing.JLabel lbOrdem;
    private javax.swing.JTable tbUsuario;
    private javax.swing.JTextPane tfInstituicao;
    private javax.swing.JTextPane tfNome;
    // End of variables declaration//GEN-END:variables
}
