package View;
import Model.ModelAdministrador;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author dklug
 */
public class ViewManutencaoAdministrador extends javax.swing.JFrame {
    
    private View view;
    String modo;

    /**
     * Creates new form ViewUsuario
     */
 ViewManutencaoAdministrador(View view) {
        this.view = view;
        initComponents();
        LoadTable();
    }

    private void LoadTable() {
        DefaultTableModel modelo = new DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Nome", "Cargo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        };
        for (int i = 0; i < this.view.getAdministradores().size(); i++) {
            Object linha[] = new Object[] { this.view.getAdministradores().get(i).getCodigo(),
                                                            this.view.getAdministradores().get(i).getNome(),
                                                            this.view.getAdministradores().get(i).getCargo()};
            modelo.addRow(linha);
        }
        tbMotorista.setModel(modelo);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbMotorista = new javax.swing.JTable();
        btAdicionar = new javax.swing.JButton();
        btEditar = new javax.swing.JButton();
        btExcluir = new javax.swing.JButton();
        lbNome = new javax.swing.JLabel();
        lbCargo = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tfNome = new javax.swing.JTextPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        tfCargo = new javax.swing.JTextPane();
        btSalvar = new javax.swing.JButton();
        btCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tbMotorista.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Nome", "Cargo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbMotorista.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbMotoristaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbMotorista);
        if (tbMotorista.getColumnModel().getColumnCount() > 0) {
            tbMotorista.getColumnModel().getColumn(0).setResizable(false);
        }

        btAdicionar.setText("Adicionar");
        btAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAdicionarActionPerformed(evt);
            }
        });

        btEditar.setText("Editar");
        btEditar.setEnabled(false);
        btEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEditarActionPerformed(evt);
            }
        });

        btExcluir.setText("Excluir");
        btExcluir.setEnabled(false);
        btExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExcluirActionPerformed(evt);
            }
        });

        lbNome.setText("Nome:");

        lbCargo.setText("Cargo:");

        tfNome.setEnabled(false);
        jScrollPane2.setViewportView(tfNome);

        tfCargo.setEnabled(false);
        jScrollPane3.setViewportView(tfCargo);

        btSalvar.setText("Salvar");
        btSalvar.setEnabled(false);
        btSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalvarActionPerformed(evt);
            }
        });

        btCancelar.setText("Cancelar");
        btCancelar.setToolTipText("");
        btCancelar.setEnabled(false);
        btCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btAdicionar, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbCargo)
                            .addComponent(lbNome))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btAdicionar)
                    .addComponent(btEditar)
                    .addComponent(btExcluir))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbNome))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbCargo)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btSalvar)
                    .addComponent(btCancelar))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAdicionarActionPerformed
        modo = "Novo";
        manipularInterface();
    }//GEN-LAST:event_btAdicionarActionPerformed

    private void btSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalvarActionPerformed
        if (modo.equals("Novo")) {
            ModelAdministrador administrador = new ModelAdministrador(tfNome.getText(), tfCargo.getText());
            this.view.salvarAdministrador(administrador);
        } else if (modo.equals("Editar")) {
             int index = tbMotorista.getSelectedRow();
            ModelAdministrador administrador = new ModelAdministrador(this.view.getAdministradores().get(index).getCodigo(),tfNome.getText(), tfCargo.getText());
                this.view.editarAdministrador(administrador);
        }

        modo = "Visualizar";
        manipularInterface();
        LoadTable();
    }//GEN-LAST:event_btSalvarActionPerformed

    private void btCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelarActionPerformed
        modo = "Visualizar";
        manipularInterface();
    }//GEN-LAST:event_btCancelarActionPerformed

    private void tbMotoristaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbMotoristaMouseClicked
        int index = tbMotorista.getSelectedRow();
        if (index >= 0 && index < this.view.getAdministradores().size()) {
            modo = "Selecionar";
            manipularInterface();  
            tfNome.setText(this.view.getAdministradores().get(index).getNome());
            tfCargo.setText(this.view.getAdministradores().get(index).getCargo());
        }
    }//GEN-LAST:event_tbMotoristaMouseClicked

    private void btEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEditarActionPerformed
        modo = "Editar";
        manipularInterface();
    }//GEN-LAST:event_btEditarActionPerformed

    private void btExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExcluirActionPerformed

        int index = tbMotorista.getSelectedRow();
        if (index >= 0 && index < this.view.getAdministradores().size()) {
            int confirmacao = JOptionPane.YES_NO_OPTION;
            int excluir = JOptionPane.showConfirmDialog (null, "Deseja excluir esse administrador?","Warning",confirmacao);
                if(excluir == JOptionPane.YES_OPTION) {
                    this.view.excluirAdministrador(this.view.getAdministradores().get(index).getCodigo());
                }
        }
        LoadTable();
        modo = "Visualizar";
        manipularInterface();
    }//GEN-LAST:event_btExcluirActionPerformed

    private void manipularInterface () {
        switch (modo) {
            case "Visualizar":
                btAdicionar.setEnabled(true);
                btEditar.setEnabled(false);
                btExcluir.setEnabled(false);
                btSalvar.setEnabled(false);
                btCancelar.setEnabled(false);
                tfNome.setEnabled(false);
                tfCargo.setEnabled(false);
                tfNome.setText("");
                tfCargo.setText("");
                tbMotorista.clearSelection();
                break;
                
            case "Selecionar":
                btAdicionar.setEnabled(true);
                btEditar.setEnabled(true);
                btExcluir.setEnabled(true);
                btSalvar.setEnabled(false);
                btCancelar.setEnabled(false);
                tfNome.setEnabled(false);
                tfCargo.setEnabled(false);
                break;
            
            case "Novo":
                btAdicionar.setEnabled(false);
                btEditar.setEnabled(false);
                btExcluir.setEnabled(false);
                btSalvar.setEnabled(true);
                btCancelar.setEnabled(true);
                tfNome.setEnabled(true);
                tfCargo.setEnabled(true);
                tfNome.setText("");
                tfCargo.setText("");
                tbMotorista.clearSelection();
                break;
            
            case "Editar":
                btAdicionar.setEnabled(false);
                btEditar.setEnabled(false);
                btExcluir.setEnabled(false);
                btSalvar.setEnabled(true);
                btCancelar.setEnabled(true);
                tfNome.setEnabled(true);
                tfCargo.setEnabled(true);
                break;
                
            default: System.out.println("Modo inválido");
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAdicionar;
    private javax.swing.JButton btCancelar;
    private javax.swing.JButton btEditar;
    private javax.swing.JButton btExcluir;
    private javax.swing.JButton btSalvar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lbCargo;
    private javax.swing.JLabel lbNome;
    private javax.swing.JTable tbMotorista;
    private javax.swing.JTextPane tfCargo;
    private javax.swing.JTextPane tfNome;
    // End of variables declaration//GEN-END:variables
}
