package View;

import Model.ModelViagem;
import Model.ModelViagemPassageiroTipo;

/**
 *
 * @author dklug
 */
public class ViewVisualizarViagem extends javax.swing.JFrame {

    /**
     * Creates new form ViewViagemRelatorio
     */
    public ViewVisualizarViagem() {
        initComponents();
        
    }
    
    public void iniciaConsulta(ModelViagem viagem) {
        for(ModelViagemPassageiroTipo tipo : viagem.getListaPassageiroTipoViagem() ){
            this.taVisualizar.append(tipo.toString() + "\n ****************************************\n");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        taVisualizar = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Visualizar Viagem");

        taVisualizar.setColumns(20);
        taVisualizar.setRows(5);
        jScrollPane1.setViewportView(taVisualizar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 965, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 575, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea taVisualizar;
    // End of variables declaration//GEN-END:variables
}
