package View;


import Model.ModelViagem;
import Model.Table.TableModelViagem;
import java.awt.event.ActionListener;
import java.util.List;
import javax.swing.JOptionPane;


/**
 *
 * @author dklug
 */
public class ViewViagem extends javax.swing.JFrame {

        
    /**
     * Creates new form ViewViagem
     */
    public ViewViagem() {
        initComponents();
    }
    
    public void loadTable(List<ModelViagem> viagens) {
        TableModelViagem tableModelViagem = new TableModelViagem(viagens);
        tbViagem.setModel(tableModelViagem);
        
    }
    
    public void adicionaAcaoIncluirViagem(ActionListener acao){
        this.btIncluirViagem.addActionListener(acao);
    }
    
    public void adicionaAcaoExcluirViagem(ActionListener acao){
        this.btExcluirViagem.addActionListener(acao);
    }
    
    public void adicionaAcaoVisualizarRota(ActionListener acao){
        this.btVisualizarRota.addActionListener(acao);
    }
    
    public void adicionaAcaoIncluirPassageiro(ActionListener acao){
        this.btIncluirPassageiro.addActionListener(acao);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tbRota = new javax.swing.JScrollPane();
        tbViagem = new javax.swing.JTable();
        btExcluirViagem = new javax.swing.JButton();
        btIncluirViagem = new javax.swing.JButton();
        btVisualizarRota = new javax.swing.JButton();
        btIncluirPassageiro = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Consulta de Viagens");
        setPreferredSize(new java.awt.Dimension(1100, 730));

        tbViagem.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tbRota.setViewportView(tbViagem);

        btExcluirViagem.setText("Excluir");

        btIncluirViagem.setText("Nova Viagem");

        btVisualizarRota.setText("Visualizar viagem");

        btIncluirPassageiro.setText("Incluir Passageiro");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tbRota, javax.swing.GroupLayout.DEFAULT_SIZE, 1088, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btIncluirViagem, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btExcluirViagem, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btVisualizarRota)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btIncluirPassageiro, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btVisualizarRota)
                    .addComponent(btIncluirPassageiro))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tbRota, javax.swing.GroupLayout.PREFERRED_SIZE, 514, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btExcluirViagem)
                    .addComponent(btIncluirViagem))
                .addContainerGap(101, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
 
    
    public void exibeMensagem(String titulo, String mensagem, int tipo) {
        JOptionPane.showMessageDialog(null, mensagem, titulo, tipo);
    }
    
    public int exibeMensagemCofirmacao(String titulo, String mensagem, int tipo) {
        return JOptionPane.showConfirmDialog (null, mensagem, titulo, tipo);
    }
    
    public int getIndiceLinhaTabela() {
        return this.tbViagem.getSelectedRow();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btExcluirViagem;
    private javax.swing.JButton btIncluirPassageiro;
    private javax.swing.JButton btIncluirViagem;
    private javax.swing.JButton btVisualizarRota;
    private javax.swing.JScrollPane tbRota;
    private javax.swing.JTable tbViagem;
    // End of variables declaration//GEN-END:variables

}
